### ISSUE TITLE
pmb.plot_dependence fails for BartRV due to missing `owner`

### ISSUE THREAD

**Issue by Visdoom** [pymc-devs/pymc-bart#77]
Hi there, 
I've been trying to recreate the Bikes example also shown in the paper (https://arxiv.org/pdf/2206.03619.pdf) 
and I fail to get the `pmb.plot_dependence()` function to work. Maybe someone of you can help me 🤷‍♀️ 

My code is 👇 
```
import pymc3 as pmc
import pymc_bart as pmb

# Prepare data
features = ["hr", "temp", "hum", "workingday"]

X = bikes_data[features]
Y = bikes_data["cnt"]

# Set up model and train
with pmc.Model() as model:

    µ = pmc.BART('µ', X, Y, m=50)
    σ = pmc.HalfNormal('σ', Y.std())
    y = pmc.Normal('y', µ, σ, observed=Y)
    idata_bikes = pmc.sample(1000, return_inferencedata=False, random_seed=42)
    posterior_predictive = pmc.sample_posterior_predictive(idata_bikes, random_seed=42)
```

It trains and `μ`  holds a `BartRV` but when I try to plot the dependence 
`pmb.plot_dependence(μ,X,Y, var_discrete=[3], grid=(2,2))`

I get
```

AttributeError: 'NoneType' object has no attribute 'op'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-1938028004449966> in <cell line: 1>()
----> 1 pmb.plot_dependence(μ,X,Y, var_discrete=[3], grid=(2,2))

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a5196f7b-b8f1-41da-b3d9-a0ce6cb21bca/lib/python3.9/site-packages/pymc_bart/utils.py in plot_dependence(bartrv, X, Y, kind, xs_interval, xs_values, var_idx, var_discrete, func, samples, instances, random_seed, sharey, rug, smooth, indices, grid, color, color_mean, alpha, figsize, smooth_kwargs, ax)
    256     new_X = np.zeros_like(X)
    257     idx_s = list(range(X.shape[0]))
--> 258     all_trees = bartrv.owner.op.all_trees
    259     for i in var_idx:
    260         indices_mi = indices[:]

AttributeError: 'NoneType' object has no attribute 'op'
```
It seems that the `owner` of the BartRV is not set? How can I fix this issue?

**Comment by Visdoom** [comment]
Potential note of interest: I installed the dev version via `pip install git+https://github.com/pymc-devs/pymc-bart.git
`

**Comment by Visdoom** [comment]
Ok, so I think there is something seriously jumbled between the integration of `pymc3`, pymc_bart` and `arviz`. 
The tutorials out there work for the watermarked setup

```pandas    : 1.5.3
pymc      : 5.0.2
pymc_bart : 0.3.2
arviz     : 0.14.0
matplotlib: 3.5.2
numpy     : 1.23.5
```
but not for the current package installations. Might be good to make that more prominent or fix the needed packages in the requirements.txt

**Comment by aloctavodia** [comment]
Hi, thanks for reporting this issue.

PyMC-BART works with pymc>=0.5.0  as stated here https://github.com/pymc-devs/pymc-bart/blob/main/requirements.txt

If you run `pip install pymc-bart` you should get all the correct packages. The same with `conda install -c conda-forge pymc-bart`

Are you following the BART example from the book https://bayesiancomputationbook.com? If that's the case we recommend installing all the packages using the environment we provided here https://github.com/BayesianModelingandComputationInPython/BookCode_Edition1#conda
